version: '3'
services:
  web:
    container_name: "portfolio_app"
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    expose:
      - 3000